openapi: 3.0.4

info:
  title: APEx Dispatch API
  description: >-
    Implementation of the APEx Dispatch Service API to support the execution of
    single job executions or upscaling tasks for APEx-compliant services.
  version: 1.0.0

security:
  - apex_auth: [openid, email, profile]
tags:
  - name: Upscale Tasks
    description: Operations related to upscaling tasks.
  - name: Unit Jobs
    description: Operations related to individual processing jobs.

paths:

  /jobs_status:
    get:
      tags:
        - Upscale Tasks
        - Unit Jobs
      summary: >-
        Get a list of all upscaling tasks & processing jobs for the
        authenticated user.
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            default: 50
          description: Max number of results
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
          description: Offset for pagination
      responses:
        '200':
          description: >-
            Successfully retrieved the user's processing jobs and upscaling
            tasks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobsStatusResponse'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        
  /tiles:
    post:
      tags:
        - Upscale Tasks
      summary: Split an area of interest in a list of tiles.
      description: >-
        Given a certain area of interest and a tiling grid definition (from the
        service’s Max AOI capacity), calculate the number of tiles to be
        processed by the upscaling service.
      requestBody:
        description: Request the tiles to be processed.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TileRequest'
        required: true
      responses:
        '201':
          description: Successfully calculated tiles
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TileResponse'
        '400':
          description: Grid ID is not supported
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        
  /upscale_tasks:
    post:
      tags:
        - Upscale Tasks
      summary: Create a new upscaling task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpscaleRequest'
      responses:
        '201':
          description: Successfully created upscaling task
          headers:
            Location:
              description: URL of the created upscaling task
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpscalingTaskSummary'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        
  /upscale_tasks/{taskID}:
    get:
      tags:
        - Upscale Tasks
      summary: Retrieve details of an upscaling task
      parameters:
        - in: path
          name: taskID
          schema:
            type: integer
          required: true
          description: ID of the upscaling task to retrieve
      responses:
        '200':
          description: Upscaling task details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpscalingTask'
        '404':
          description: Could not find the upscaling task for the provided ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        
  /unit_jobs:
    post:
      tags:
        - Unit Jobs
      summary: Create a new processing job
      requestBody:
        required: true
        description: Details of the processing job to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseJobRequest'
      responses:
        '201':
          description: Successfully created a single processing job
          headers:
            Location:
              description: URL of the created processing job
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessingJobSummary'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        
  /unit_jobs/{jobID}:
    get:
      tags:
        - Unit Jobs
      summary: Retrieve details of a processing job.
      parameters:
        - in: path
          name: jobID
          schema:
            type: integer
          required: true
          description: ID of the processing job to retrieve
      responses:
        '200':
          description: Processing job details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessingJob'
        '404':
          description: Could not find the processing job for the provided ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    TileRequest:
      type: object
      required:
        - aoi
        - grid
      properties:
        aoi:
          type: object
          description: 'GeoJSON Feature using coordinates in EPSG:4326'
          example:
            type: Feature
            geometry: {}
        grid:
          type: string
          example: S2_UTM_TILING_GRID
          enum:
            - S2_UTM_TILING_GRID
            
    TileResponse:
      type: object
      properties:
        tiles:
          type: array
          items:
            $ref: '#/components/schemas/Tile'
            
            
    BaseJobRequest:
      type: object
      required:
        - label
        - title
        - service
        - parameters
      properties:
        title:
          type: string
          description: Title of the job
        label:
          $ref: '#/components/schemas/ProcessType'
        service:
          $ref: '#/components/schemas/ServiceDetails'
        parameters:
          $ref: '#/components/schemas/ServiceParameters'
            
    UpscaleRequest:
      type: object
      required:
        - label
        - tiles
        - title
        - service
        - parameters
      allOf:
        - $ref: '#/components/schemas/BaseJobRequest'
        - type: object
          properties:
            tiles:
              type: array
              items:
                $ref: '#/components/schemas/Tile'
                
    JobsStatusResponse:
      type: object
      properties:
        upscalingTasks:
          type: array
          items:
            $ref: '#/components/schemas/UpscalingTaskSummary'
        processingJobs:
          type: array
          items:
            $ref: '#/components/schemas/ProcessingJobSummary'
            
    ServiceDetails:
      type: object
      description: Details of the service to be executed
      required:
        - id
      properties:
        id:
          type: string
          
    ServiceParameters:
      type: object
      description: >-
        Object containing the parameters that need to be provided to the service
        execution
        
    ProcessingJobSummary:
      type: object
      description: Summary of an processing job
      required:
        - id
        - title
        - status
      properties:
        id:
          type: integer
          description: ID of the processing job
        title:
          type: string
          description: Title of the processing job
          example: My processing job
        status:
          $ref: '#/components/schemas/ProcessingStatus'
          
    ProcessingJobDetails:
      type: object
      required:
        - label
        - service
        - parameters
      properties:
        label:
          $ref: '#/components/schemas/ProcessType'
        service:
          $ref: '#/components/schemas/ServiceDetails'
        parameters:
          $ref: '#/components/schemas/ServiceParameters'
        
    ProcessingJob:
      type: object
      description: Description of the processing job
      allOf:
        - $ref: '#/components/schemas/ProcessingJobSummary'
        - $ref: '#/components/schemas/ProcessingJobDetails'
        
    
    UpscalingTaskSummary:
      type: object
      description: Summary of an upscaling task
      required:
        - id
        - title
        - status
      properties:
        id:
          type: integer
          description: ID of the upscaling task
        title:
          type: string
          description: Title of the upscale task
          example: My upscale task
        status:
          $ref: '#/components/schemas/ProcessingStatus'
    
    UpscalingTaskDetails:
      type: object
      required:
        - label
        - service
        - parameters
        - jobs
      properties:
        label:
          $ref: '#/components/schemas/ProcessType'
        service:
          $ref: '#/components/schemas/ServiceDetails'
        parameters:
          $ref: '#/components/schemas/ServiceParameters'
        jobs:
          type: array
          items:
            $ref: '#/components/schemas/ProcessingJob'
          
    UpscalingTask:
      type: object
      description: Details of an upscaling task
      allOf:
        - $ref: '#/components/schemas/UpscalingTaskSummary'
        - $ref: '#/components/schemas/UpscalingTaskDetails'
           
    Tile:
      type: object
      description: 'GeoJSON Feature using coordinates in EPSG:4326'
      example:
        type: Feature
        geometry: {}
        
    ProcessType:
      type: string
      description: Label indicating that the type of service that is going to be executed.
      enum:
        - OPENEO
        - OGC_API_PROCESS
        
    ProcessingStatus:
      type: string
      description: Status of the processing
      enum:
        - CREATED
        - RUNNING
        - FINISHED
        - FAILED
  
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object
        
  securitySchemes:
    apex_auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'http://auth.apex.esa.int/realms/apex/protocol/openid-connect/auth'
          tokenUrl: 'http://auth.apex.esa.int/realms/apex/protocol/openid-connect/token'
          scopes:
            openid: OpenID Connect scope
            profile: User profile
            email: Email address
