"""processing_jobs: rename of service_record field

Revision ID: 6105be2a2b21
Revises: a0ca6614c7c1
Create Date: 2025-08-20 16:55:05.666856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6105be2a2b21'
down_revision: Union[str, Sequence[str], None] = 'a0ca6614c7c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('service', sa.String(), nullable=False))
    op.drop_index(op.f('ix_processing_jobs_service_record'), table_name='processing_jobs')
    op.create_index(op.f('ix_processing_jobs_service'), 'processing_jobs', ['service'], unique=False)
    op.drop_column('processing_jobs', 'service_record')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('service_record', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_processing_jobs_service'), table_name='processing_jobs')
    op.create_index(op.f('ix_processing_jobs_service_record'), 'processing_jobs', ['service_record'], unique=False)
    op.drop_column('processing_jobs', 'service')
    # ### end Alembic commands ###
