"""Add label to processing jobs

Revision ID: adc8ba536dea
Revises: 3b5001cdded8
Create Date: 2025-08-11 16:55:30.516798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc8ba536dea'
down_revision: Union[str, Sequence[str], None] = '3b5001cdded8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('label', sa.String(), nullable=True))
    op.create_index(op.f('ix_processing_jobs_label'), 'processing_jobs', ['label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_jobs_label'), table_name='processing_jobs')
    op.drop_column('processing_jobs', 'label')
    # ### end Alembic commands ###
