"""Creation of processing jobs

Revision ID: b3ba8db2adef
Revises: 
Create Date: 2025-08-13 09:37:59.014491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ba8db2adef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('label', sa.Enum('OPENEO', 'OGC_API_PROCESS', name='processtypeenum'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'RUNNING', 'FINISHED', 'FAILED', name='processingstatusenum'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('platform_job_id', sa.String(), nullable=True),
    sa.Column('parameters', sa.String(), nullable=True),
    sa.Column('result_link', sa.String(), nullable=True),
    sa.Column('service_record', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_created'), 'processing_jobs', ['created'], unique=False)
    op.create_index(op.f('ix_processing_jobs_id'), 'processing_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_label'), 'processing_jobs', ['label'], unique=False)
    op.create_index(op.f('ix_processing_jobs_platform_job_id'), 'processing_jobs', ['platform_job_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_service_record'), 'processing_jobs', ['service_record'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_processing_jobs_title'), 'processing_jobs', ['title'], unique=False)
    op.create_index(op.f('ix_processing_jobs_updated'), 'processing_jobs', ['updated'], unique=False)
    op.create_index(op.f('ix_processing_jobs_user_id'), 'processing_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_jobs_user_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_updated'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_title'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_service_record'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_platform_job_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_label'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_created'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    # ### end Alembic commands ###
