"""platform job id becomes optional

Revision ID: be54acd4d160
Revises: 8a69e1ee3fef
Create Date: 2025-08-25 11:41:54.963734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be54acd4d160'
down_revision: Union[str, Sequence[str], None] = '8a69e1ee3fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processing_jobs', 'platform_job_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processing_jobs', 'platform_job_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
