"""Update of processing jobs

Revision ID: dbc9c2bd9a57
Revises: b3ba8db2adef
Create Date: 2025-08-13 18:00:40.408757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc9c2bd9a57'
down_revision: Union[str, Sequence[str], None] = 'b3ba8db2adef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processing_jobs', 'platform_job_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('processing_jobs', 'parameters',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('processing_jobs', 'service_record',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processing_jobs', 'service_record',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('processing_jobs', 'parameters',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('processing_jobs', 'platform_job_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
