apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apex-dispatch-api.fullname" . }}-config
data:
  APP_NAME: {{ .Values.app.name | quote }}
  APP_ENV: {{ .Values.app.environment | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.app.corsAllowedOrigins | quote }}
  KEYCLOAK_HOST: {{ .Values.keycloak.host | quote }}
  KEYCLOAK_REALM: {{ .Values.keycloak.realm | quote }}